# Jekyll Settings
excerpt_separator: <!--more-->
exclude: ["CNAME", "README.md", "LICENSE"]
paginate: 5
paginate_path: ":num"
permalink: pretty
sass:
    style: :compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Custom Variables
author:
  email: "&#x57;&#x65;&#x6E;&#x78;&#x75;&#x61;&#x6E;&#x2E;&#x47;&#x75;&#x6F;&#x40;&#x6D;&#x79;&#x2E;&#x63;&#x69;&#x74;&#x79;&#x75;&#x2E;&#x65;&#x64;&#x75;&#x2E;&#x68;&#x6B;"
  github: "magwx"
  name: "&#x57;&#x65;&#x6E;&#x78;&#x75;&#x61;&#x6E;&#x20;&#x47;&#x75;&#x6F;"
  uri: "https://magwx.github.io"
description: "Personal website of GWX."
title: "&#x44;&#x72;&#x2E;&#x20;&#x57;&#x65;&#x6E;&#x78;&#x75;&#x61;&#x6E;&#x20;&#x47;&#x75;&#x6F;"
sidetitle: ["&#x57;&#x65;&#x6E;&#x78;&#x75;&#x61;&#x6E;", "&#x47;&#x75;&#x6F;"]
url: "https://magwx.github.io"
